language: go
go:
  - 1.11.x
  - master
env:
  - GO111MODULE=on
before_install:
  - sudo pip install codecov
script:
  - make ci
after_script:
  - codecov
cache:
  directories:
    - /go/pkg/mod/cache/download
    - /go/src/github.com