version: '3'
services:
  qc-web:
    build: ./docker
    image: qc-php73-apache
    hostname: qc-web
    container_name: qc-web
    volumes:
      - ./docker/laravel-app:/var/www/html:cached
      - ./docker/tcpdp/tcpdp-config.toml:/etc/tcpdp-config.toml:cached
      - ./docker/tcpdp/logs:/var/log/tcpdp:cached
    networks:
      app_net:
        ipv4_address: 10.200.200.2
    ports:
      - "8000:80"
    depends_on:
      - qc-db

  qc-db:
    image: mysql:5.7
    hostname: qc-db
    container_name: qc-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:cached
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:cached
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:cached
    networks:
      app_net:
        ipv4_address: 10.200.200.3
    ports:
      - "3306:3306"

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.200.200.0/24
